name: Test Secrets

on: 
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  test_secrets_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test if secret is available
        run: echo "Secret is available!"
        env:
          MY_SECRET: ${{ secrets.FREE_CURRENCY_API_KEY }}
